[project]
site_name = "The Python driver for Firebird"
site_author = "Pavel Císař"
copyright = "The Firebird Project"
site_url = "https://firebird-driver.readthedocs.io/"
nav = [
  { "Home" = "index.md" },
  { "Getting Started" = "getting-started.md" },
  { "Usage Guide" = [
    { "Driver structure" = "usage-guide/driver-structure.md" },
    { "Configuration" = "usage-guide/configuration.md" },
    { "Databases" = "usage-guide/databases.md" },
    { "Executing SQL Statements" = "usage-guide/executing-sql-statements.md" },
    { "Data handling and conversions" = "usage-guide/data-handling-and-conversions.md" },
    { "Transactions" = "usage-guide/transactions.md" },
    { "Database Events" = "usage-guide/database-events.md" },
    { "Working with Services" = "usage-guide/working-with-services.md" },
    { "Logging driver activities" = "usage-guide/logging-driver-activities.md" },
    { "Driver hooks" = "usage-guide/driver-hooks.md" },
  ] },
  { "Python DB API compliance" = "python-db-api-compliance.md" },
  { "Reference" = [
    { "Main namespace" = "ref-main.md" },
    { "Types" = "ref-types.md" },
    { "Configuration" = "ref-config.md" },
    { "Core" = "ref-core.md" },
    { "Hooks" = "ref-hooks.md" },
    { "Interfaces" = "ref-intf.md" },
    { "Client API" = "ref-fbapi.md" },
  ] },
  { "Changelog" = "changelog.md" },
  { "License" = "license.md" },
]

[project.theme]
favicon = "assets/fb-favicon.png"
features = [
    "navigation.instant",
    "navigation.tracking",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.sections",
    "navigation.expand",
    "navigation.path",
    "navigation.top",
]

[project.plugins.mkdocstrings.handlers.python]
paths = ["../src"]
inventories = ["https://docs.python.org/3/objects.inv"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = true
show_root_heading = true
show_source = true
